// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvhWQTt5cphZ1dRNUMfHybVqN8h2n1bmM',
    appId: '1:726979419525:web:2c058525d9f04feca4b8ec',
    messagingSenderId: '726979419525',
    projectId: 'animal-lover-app-e4f75',
    authDomain: 'animal-lover-app-e4f75.firebaseapp.com',
    storageBucket: 'animal-lover-app-e4f75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_0HmZAKRp9S99aGpVz20-0zayFHpzNs',
    appId: '1:726979419525:android:fa78ef6341f7e820a4b8ec',
    messagingSenderId: '726979419525',
    projectId: 'animal-lover-app-e4f75',
    storageBucket: 'animal-lover-app-e4f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2I0mYDDrMa_Im02V-p4E9dfnzxOh8-4A',
    appId: '1:726979419525:ios:a71218d2f33c2befa4b8ec',
    messagingSenderId: '726979419525',
    projectId: 'animal-lover-app-e4f75',
    storageBucket: 'animal-lover-app-e4f75.firebasestorage.app',
    iosBundleId: 'com.example.animalLover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2I0mYDDrMa_Im02V-p4E9dfnzxOh8-4A',
    appId: '1:726979419525:ios:a71218d2f33c2befa4b8ec',
    messagingSenderId: '726979419525',
    projectId: 'animal-lover-app-e4f75',
    storageBucket: 'animal-lover-app-e4f75.firebasestorage.app',
    iosBundleId: 'com.example.animalLover',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvhWQTt5cphZ1dRNUMfHybVqN8h2n1bmM',
    appId: '1:726979419525:web:892bd08e1dc0da5ca4b8ec',
    messagingSenderId: '726979419525',
    projectId: 'animal-lover-app-e4f75',
    authDomain: 'animal-lover-app-e4f75.firebaseapp.com',
    storageBucket: 'animal-lover-app-e4f75.firebasestorage.app',
  );
}
